development:
  adapter: postgresql
  encoding: unicode
  database: HomeApp_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: HomeApp_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: HomeApp_production
  pool: 5
  username: HomeApp
  password: <%= ENV['LENDIFY_DBPASS'] %>
